### ISSUE TITLE
Exporter Ocagent not propagating serviceName

### ISSUE THREAD

**Issue by drubin** [census-instrumentation/opencensus-node#630]
Sorry if this is the wrong place to report this. I might also be using this incorrectly I couldn't find much documentation on how to use this with opencensus agent/collector.
### What version of OpenCensus are you using?

    "@opencensus/exporter-ocagent": "0.0.15",
    "@opencensus/nodejs": "0.0.15",

Docker version omnition/opencensus-collector:0.1.9

### What version of Node are you using?
v10.15.3

### What did you do?
I am trying to get my node application to that is instrumented with open census via the proxy to multiple services.

api->collector->honeycomb
api->collector->jeager 

```js
const tracing = require('@opencensus/nodejs')
const ocagent = require('@opencensus/exporter-ocagent')
const exporter = new ocagent.OCAgentExporter({
  serviceName: 'api',
  host: 'opencensus-collector',
  port: 55678,
  logger: console
  // ... configuration options ...
})

tracing.registerExporter(exporter).start()
```

Config for opencensus-collector 

```yml
receivers:
  opencensus:
    address: ":55678"

exporters:
  jaeger:
    collector_endpoint: "http://jaeger:14268/api/traces"
  honeycomb:
    write_key: "na"
    dataset_name: "dataset-node-js"
```

Trying to export the service name via a collector agent to either jaeger and honeycomb.

### What did you expect to see?

The trace data does appear in both honeycomb and jeager but the serviceName doesn't seem to be passed through

I expect the service name to be `api` but instead, the service is listed as `OpenCensus` and in honeycomb, the serviceName doesn't even exist. Does this come from the collector (i.e opencensus-collector) or is it not being passed upstream

### What did you see instead?

I expect the service's name to be `api` in both Jeager and Honeycomb.

### Additional context

Sorry if this is a bug that belongs in the collector if so, i can move it over there once I know the cause is actually in the collector.
